spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: image-service-id
          uri: http://localhost:8081/
          predicates:
            - Path=/image/**
        - id: gallery-service-id
          uri: http://localhost:8082/
          predicates:
            - Path=/gallery/**

server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
