spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service-id
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthFilter
        - id: image-service-id
          uri: lb://image-service
          predicates:
            - Path=/image/**
        #          filters:
        #            - AuthFilter
        - id: gallery-service-id
          uri: lb://gallery-service
          predicates:
            - Path=/gallery/**
#          filters:
#            - AuthFilter

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

excluded-urls: >
  /auth/api/login,
  /auth/api/info  
