spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      auto-index-creation: true
      database: user
      uri: mongodb://127.0.0.1:27017/user
server:
  port: 8084
  servlet:
    context-path: /user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
