spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      auto-index-creation: true
      database: user
      uri: mongodb://127.0.0.1:27017/user
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8085
  servlet:
    context-path: /auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
redis:
  host: 127.0.0.1
  port: 6379

jwt:
  secret: VmVuZXNhSVQhQDIwMjBTZWNyZXRrZXlTcGFBbmRHeW1KV1Q=
  time-token: 1800
